import type { Difficulty } from '@/types'

export const wordLists: Record<Difficulty, string[]> = {
  easy: [
    // 200 common short English words
    'the', 'and', 'for', 'are', 'but', 'not', 'you', 'all', 'can', 'had',
    'her', 'him', 'his', 'how', 'man', 'new', 'now', 'old', 'see', 'two',
    'way', 'who', 'boy', 'did', 'its', 'let', 'put', 'say', 'she', 'too',
    'use', 'was', 'get', 'big', 'day', 'end', 'far', 'few', 'got', 'has',
    'hot', 'job', 'key', 'law', 'lay', 'led', 'log', 'lot', 'low', 'mad',
    'map', 'may', 'met', 'mix', 'net', 'nor', 'off', 'one', 'our', 'out',
    'own', 'pay', 'per', 'ran', 'raw', 'red', 'run', 'set', 'sit', 'six',
    'sky', 'son', 'top', 'try', 'cut', 'bit', 'bag', 'bat', 'bed', 'bet',
    'box', 'bus', 'buy', 'cat', 'cup', 'dog', 'dot', 'dry', 'dug', 'ear',
    'eat', 'egg', 'eye', 'fat', 'fly', 'fun', 'gap', 'gas', 'gun', 'gut',
    'gym', 'hat', 'hit', 'hop', 'hub', 'hug', 'ice', 'ill', 'ink', 'inn',
    'jar', 'jaw', 'joy', 'jug', 'kit', 'lab', 'lag', 'lap', 'leg', 'lid',
    'lip', 'lit', 'mad', 'mug', 'nap', 'net', 'nod', 'nun', 'oak', 'odd',
    'oil', 'opt', 'orb', 'pad', 'pan', 'pat', 'paw', 'peg', 'pen', 'pet',
    'pie', 'pig', 'pin', 'pit', 'pod', 'pop', 'pot', 'pub', 'pug', 'rat',
    'rib', 'rid', 'rip', 'rod', 'rot', 'rub', 'rug', 'rum', 'sad', 'sap',
    'sat', 'saw', 'sew', 'sin', 'sip', 'sob', 'sod', 'sow', 'spa', 'spy',
    'stir', 'sub', 'sum', 'sun', 'sup', 'tab', 'tan', 'tap', 'tar', 'tax',
    'tip', 'toe', 'ton', 'toy', 'tug', 'tun', 'van', 'vat', 'vet', 'vow',
    'wag', 'war', 'web', 'wed', 'wet', 'win', 'wit', 'woe', 'won', 'woo',
  ],

  medium: [
    // 500 words — easy words + medium complexity + contractions
    'the', 'and', 'for', 'are', 'but', 'not', 'you', 'all', 'can', 'had',
    'her', 'him', 'his', 'how', 'man', 'new', 'now', 'old', 'see', 'two',
    'way', 'who', 'boy', 'did', 'its', 'let', 'put', 'say', 'she', 'too',
    'use', 'was', 'get', 'big', 'day', 'end', 'far', 'few', 'got', 'has',
    'hot', 'job', 'key', 'law', 'lay', 'led', 'log', 'lot', 'low', 'mad',
    'map', 'may', 'met', 'mix', 'net', 'nor', 'off', 'one', 'our', 'out',
    'own', 'pay', 'per', 'ran', 'raw', 'red', 'run', 'set', 'sit', 'six',
    'sky', 'son', 'top', 'try', 'cut', 'bit', 'bag', 'bat', 'bed', 'bet',
    'box', 'bus', 'buy', 'cat', 'cup', 'dog', 'dot', 'dry', 'dug', 'ear',
    'eat', 'egg', 'eye', 'fat', 'fly', 'fun', 'gap', 'gas', 'gun', 'gut',
    'about', 'after', 'again', 'also', 'back', 'been', 'call', 'came', 'come',
    'does', 'down', 'each', 'even', 'find', 'from', 'give', 'good', 'great',
    'have', 'here', 'high', 'hold', 'home', 'into', 'just', 'keep', 'know',
    'last', 'left', 'life', 'like', 'line', 'long', 'look', 'made', 'make',
    'many', 'more', 'most', 'move', 'much', 'must', 'name', 'need', 'next',
    'open', 'over', 'part', 'past', 'play', 'read', 'real', 'same', 'show',
    'side', 'some', 'such', 'take', 'than', 'them', 'then', 'they', 'this',
    'time', 'turn', 'upon', 'used', 'very', 'want', 'well', 'were', 'what',
    'when', 'with', 'word', 'work', 'year', 'your', 'also', 'area', 'base',
    'body', 'book', 'both', 'city', 'code', 'data', 'door', 'draw', 'ever',
    'face', 'fact', 'feel', 'file', 'fill', 'fire', 'five', 'food', 'form',
    'four', 'free', 'full', 'girl', 'give', 'glad', 'goes', 'gone', 'grew',
    'grow', 'half', 'hand', 'hard', 'head', 'hear', 'held', 'help', 'hide',
    'idea', 'join', 'kind', 'king', 'knew', 'land', 'lead', 'lean', 'load',
    'loss', 'love', 'main', 'mark', 'mean', 'meet', 'mind', 'mine', 'miss',
    'mode', 'note', 'once', 'only', 'page', 'pain', 'pair', 'park', 'pass',
    'path', 'pick', 'plan', 'plus', 'poll', 'pool', 'poor', 'port', 'post',
    'pull', 'push', 'quit', 'race', 'rain', 'rank', 'rate', 'role', 'room',
    'rose', 'rule', 'safe', 'sail', 'sale', 'salt', 'sand', 'save', 'scan',
    'seal', 'seem', 'send', 'sign', 'sink', 'size', 'skin', 'slow', 'snap',
    'snow', 'soft', 'soil', 'sold', 'sole', 'song', 'soon', 'sort', 'soul',
    'span', 'spin', 'spot', 'stay', 'step', 'stop', 'sued', 'suit', 'sure',
    'swim', 'tail', 'tall', 'task', 'team', 'tend', 'tent', 'test', 'text',
    'that', 'thin', 'tied', 'till', 'told', 'toll', 'tone', 'took', 'tool',
    'town', 'tree', 'trim', 'trip', 'true', 'tube', 'type', 'unit', 'user',
    'vast', 'view', 'vote', 'wade', 'wage', 'wait', 'walk', 'wall', 'warm',
    'warn', 'wash', 'weak', 'week', 'went', 'wide', 'wife', 'wild', 'will',
    'wind', 'wine', 'wing', 'wire', 'wise', 'wish', 'wood', 'worn', 'wrap',
    'yard', 'zone', 'zone', 'able', 'bold', 'born', 'both', 'burn', 'calm',
    'card', 'care', 'case', 'cash', 'cast', 'cave', 'cell', 'chat', 'chin',
    'chip', 'cite', 'clam', 'clap', 'clay', 'clip', 'club', 'clue', 'coal',
    'coat', 'coin', 'cold', 'cope', 'cord', 'core', 'cork', 'corn', 'cost',
    'cozy', 'crew', 'crop', 'cure', 'curl', 'damp', 'dark', 'dart', 'dash',
    'dead', 'deal', 'dean', 'dear', 'debt', 'deck', 'deed', 'deem', 'deep',
    "can't", "don't", "won't", "it's", "isn't", "doesn't", "haven't",
    "couldn't", "wouldn't", "shouldn't", "I'm", "you're", "we're", "they're",
    "that's", "he's", "she's", "it'll", "we'll", "you'll", "they'll",
    "I've", "you've", "we've", "they've", "I'll", "there's", "here's",
    // Additional medium words to reach 500
    'able', 'bold', 'born', 'burn', 'calm', 'card', 'care', 'case', 'cash', 'cast',
    'cave', 'cell', 'chat', 'chin', 'chip', 'cite', 'clap', 'clay', 'clip', 'club',
    'clue', 'coal', 'coat', 'coin', 'cold', 'cope', 'cord', 'core', 'cork', 'corn',
    'cost', 'crew', 'crop', 'cure', 'curl', 'damp', 'dark', 'dart', 'dash', 'dead',
    'deal', 'dean', 'dear', 'debt', 'deck', 'deed', 'deem', 'deep', 'deny', 'desk',
    'dial', 'diet', 'dine', 'dirt', 'disk', 'dive', 'dock', 'dome', 'dose', 'dote',
    'dove', 'dram', 'drip', 'drop', 'drum', 'dual', 'duel', 'dune', 'dust', 'duty',
    'dye', 'echo', 'edit', 'emit', 'epic', 'ergo', 'even', 'exam', 'exit', 'expo',
  ],

  hard: [
    // 1000 words — medium words + rare words + numbers + symbols + complex words
    'the', 'and', 'for', 'are', 'but', 'not', 'you', 'all', 'can', 'had',
    'her', 'him', 'his', 'how', 'man', 'new', 'now', 'old', 'see', 'two',
    'way', 'who', 'boy', 'did', 'its', 'let', 'put', 'say', 'she', 'too',
    'use', 'was', 'get', 'big', 'day', 'end', 'far', 'few', 'got', 'has',
    'hot', 'job', 'key', 'law', 'lay', 'led', 'log', 'lot', 'low', 'mad',
    'about', 'after', 'again', 'also', 'back', 'been', 'call', 'came', 'come',
    'does', 'down', 'each', 'even', 'find', 'from', 'give', 'good', 'great',
    'have', 'here', 'high', 'hold', 'home', 'into', 'just', 'keep', 'know',
    'last', 'left', 'life', 'like', 'line', 'long', 'look', 'made', 'make',
    'many', 'more', 'most', 'move', 'much', 'must', 'name', 'need', 'next',
    'open', 'over', 'part', 'past', 'play', 'read', 'real', 'same', 'show',
    'side', 'some', 'such', 'take', 'than', 'them', 'then', 'they', 'this',
    'time', 'turn', 'upon', 'used', 'very', 'want', 'well', 'were', 'what',
    'when', 'with', 'word', 'work', 'year', 'your', 'area', 'base', 'body',
    'book', 'both', 'city', 'code', 'data', 'door', 'draw', 'ever', 'face',
    'fact', 'feel', 'file', 'fill', 'fire', 'five', 'food', 'form', 'four',
    'free', 'full', 'girl', 'glad', 'goes', 'gone', 'grew', 'grow', 'half',
    'hand', 'hard', 'head', 'hear', 'held', 'help', 'hide', 'idea', 'join',
    'kind', 'king', 'knew', 'land', 'lead', 'lean', 'load', 'loss', 'love',
    'main', 'mark', 'mean', 'meet', 'mind', 'mine', 'miss', 'mode', 'note',
    'once', 'only', 'page', 'pain', 'pair', 'park', 'pass', 'path', 'pick',
    'plan', 'plus', 'poll', 'pool', 'poor', 'port', 'post', 'pull', 'push',
    'quit', 'race', 'rain', 'rank', 'rate', 'role', 'room', 'rose', 'rule',
    'safe', 'sail', 'sale', 'salt', 'sand', 'save', 'scan', 'seal', 'seem',
    'send', 'sign', 'sink', 'size', 'skin', 'slow', 'snap', 'snow', 'soft',
    'soil', 'sold', 'sole', 'song', 'soon', 'sort', 'soul', 'span', 'spin',
    'spot', 'stay', 'step', 'stop', 'suit', 'sure', 'swim', 'tail', 'tall',
    'task', 'team', 'tend', 'tent', 'test', 'text', 'that', 'thin', 'tied',
    'till', 'told', 'toll', 'tone', 'took', 'tool', 'town', 'tree', 'trim',
    'trip', 'true', 'tube', 'type', 'unit', 'user', 'vast', 'view', 'vote',
    'wade', 'wage', 'wait', 'walk', 'wall', 'warm', 'warn', 'wash', 'weak',
    'week', 'went', 'wide', 'wife', 'wild', 'will', 'wind', 'wine', 'wing',
    'wire', 'wise', 'wish', 'wood', 'worn', 'wrap', 'yard', 'zone', 'able',
    "can't", "don't", "won't", "it's", "isn't", "doesn't", "haven't",
    "couldn't", "wouldn't", "shouldn't", "I'm", "you're", "we're", "they're",
    "that's", "he's", "she's", "it'll", "we'll", "you'll", "they'll",
    "I've", "you've", "we've", "they've", "I'll", "there's", "here's",
    // Numbers
    '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
    '11', '12', '15', '20', '25', '30', '50', '100', '200', '1000',
    // Symbols
    '@', '#', '&', '!', '?',
    // Complex/rare words
    'algorithm', 'necessary', 'particularly', 'approximately', 'circumstances',
    'contemporary', 'extraordinary', 'immediately', 'independent', 'occasionally',
    'phenomenon', 'preliminary', 'sophisticated', 'understanding', 'unfortunately',
    'abstraction', 'achievement', 'acknowledge', 'acquisition', 'administration',
    'affiliation', 'alternative', 'ambiguity', 'anticipate', 'application',
    'appreciate', 'architecture', 'argument', 'arrangement', 'artificial',
    'assessment', 'associated', 'assumption', 'atmosphere', 'attention',
    'authority', 'autonomous', 'background', 'bandwidth', 'behavior',
    'brilliant', 'broadcast', 'calculate', 'capability', 'challenge',
    'character', 'coalition', 'cognitive', 'commerce', 'commitment',
    'community', 'competition', 'complexity', 'component', 'conclusion',
    'condition', 'conference', 'confidence', 'conflict', 'consequence',
    'consider', 'constraint', 'container', 'content', 'context',
    'contribution', 'controller', 'coordinate', 'corruption', 'creative',
    'criterion', 'curriculum', 'database', 'decision', 'declaration',
    'definition', 'dependency', 'deployment', 'description', 'development',
    'difference', 'difficulty', 'dimension', 'direction', 'discipline',
    'discovery', 'discussion', 'distribution', 'document', 'dominant',
    'duration', 'dynamic', 'efficiency', 'element', 'eliminate',
    'emergence', 'emphasis', 'encryption', 'endpoint', 'engagement',
    'environment', 'essential', 'establish', 'evaluate', 'evolution',
    'exception', 'execution', 'existence', 'expansion', 'experience',
    'experiment', 'expression', 'extension', 'external', 'extraction',
    'facilitate', 'feedback', 'flexibility', 'foundation', 'framework',
    'frequency', 'functional', 'generated', 'graphics', 'guarantee',
    'hierarchy', 'hypothesis', 'implement', 'important', 'improvement',
    'inclusion', 'indicator', 'influence', 'information', 'infrastructure',
    'inheritance', 'innovation', 'integration', 'intelligence', 'interface',
    'iteration', 'knowledge', 'language', 'leadership', 'libraries',
    'limitation', 'management', 'mechanism', 'methodology', 'migration',
    'monitoring', 'motivation', 'namespace', 'navigation', 'objective',
    'operation', 'opportunity', 'optimization', 'organization', 'parameter',
    'performance', 'persistence', 'perspective', 'platform', 'population',
    'precision', 'principle', 'priority', 'procedure', 'prototype',
    'provision', 'qualification', 'recognition', 'recursion', 'reference',
    'relationship', 'reliability', 'requirement', 'resolution', 'resource',
    'responsibility', 'restriction', 'selection', 'separation', 'sequence',
    'serialization', 'significance', 'simulation', 'specification', 'stability',
    'statement', 'structure', 'submission', 'subsequent', 'successful',
    'sufficient', 'suggestion', 'synchronous', 'systematic', 'technology',
    'transaction', 'transition', 'transmission', 'transparency', 'validation',
    'variables', 'variation', 'visibility', 'workflow', 'abstraction',
    'capability', 'cryptography', 'declarative', 'dependency', 'encapsulation',
    'idempotent', 'immutable', 'imperative', 'inheritance', 'instantiate',
    'interpolation', 'middleware', 'polymorphism', 'refactoring', 'serialization',
    'traversal', 'webhook', 'anonymous', 'asynchronous', 'concurrent',
    'conditional', 'configuration', 'constructor', 'destructuring', 'enumerable',
    'functional', 'generator', 'immutable', 'incremental', 'initialize',
    'interceptor', 'observable', 'overloading', 'pagination', 'parallelism',
    'propagation', 'protocol', 'reactive', 'recursive', 'regression',
    'resilience', 'responsive', 'scalability', 'stateless', 'templating',
    'throughput', 'tokenization', 'typescript', 'versioning', 'visualization',
    'accomplish', 'accumulate', 'accusation', 'adaptation', 'addressable',
    'affirmative', 'allegiance', 'annotation', 'anticipation', 'apparatus',
    'appearance', 'appointment', 'articulate', 'aspiration', 'association',
    'atmosphere', 'attribution', 'automation', 'availability', 'beneficial',
    'calculation', 'calibration', 'categorical', 'centralized', 'circulation',
    'clarification', 'classification', 'collaboration', 'combination', 'commission',
    'communicate', 'comparative', 'compensation', 'compilation', 'comprehension',
    'concentration', 'consideration', 'continuation', 'controversial', 'cooperation',
    'crystallize', 'customization', 'declaration', 'decompilation', 'demonstration',
    'determination', 'disadvantage', 'disappointment', 'documentation', 'duplication',
    'elaboration', 'elimination', 'exploration', 'fundamental', 'generalization',
    'harmonization', 'identification', 'illustration', 'implementation', 'implications',
    'inconsistent', 'increasingly', 'indication', 'initialization', 'installation',
    'insufficient', 'internationalization', 'interpretation', 'introduction', 'investigation',
    'justification', 'localization', 'maximization', 'minimization', 'modification',
    'multiplication', 'normalization', 'notification', 'observations', 'optimization',
    'orchestration', 'organization', 'participation', 'permutation', 'presentation',
    'prioritization', 'production', 'quantification', 'recommendation', 'reconciliation',
    'representation', 'serialization', 'simplification', 'standardization', 'substitution',
    'transformation', 'understanding', 'verification', 'visualization', 'volatility',
    // Additional hard words to reach 1000
    'abandon', 'abbreviate', 'abolish', 'absorb', 'abstract', 'abundant', 'accelerate',
    'accurate', 'active', 'actual', 'adaptive', 'adequate', 'adjacent', 'adjust',
    'admire', 'admit', 'advance', 'affect', 'affirm', 'afford', 'aggregate',
    'agile', 'allocate', 'allow', 'analyze', 'annotate', 'answer', 'append',
    'assign', 'assure', 'attach', 'attempt', 'audit', 'augment', 'authorize',
    'balance', 'batch', 'benchmark', 'binary', 'boolean', 'bootstrap', 'bottleneck',
    'boundary', 'branch', 'buffer', 'bundle', 'bypass', 'cache', 'callback',
    'cancel', 'capture', 'cascade', 'channel', 'cipher', 'circuit', 'claim',
    'cluster', 'collapse', 'collect', 'column', 'compile', 'compute', 'connect',
    'consume', 'control', 'convert', 'copy', 'count', 'create', 'cycle',
    'debug', 'decode', 'defer', 'define', 'delete', 'deliver', 'deploy',
    'derive', 'detect', 'develop', 'disable', 'discover', 'dispatch', 'display',
    'divide', 'download', 'enable', 'encode', 'enforce', 'evaluate', 'execute',
    'export', 'extend', 'extract', 'filter', 'finalize', 'format', 'forward',
    'gather', 'generate', 'handle', 'import', 'index', 'indicate', 'inject',
    'insert', 'install', 'invoke', 'isolate', 'iterate', 'launch', 'listen',
    'lookup', 'manage', 'match', 'measure', 'merge', 'migrate', 'minimize',
    'modify', 'mount', 'notify', 'observe', 'obtain', 'optimize', 'output',
    'package', 'parse', 'pause', 'persist', 'pipeline', 'pointer', 'process',
    'produce', 'profile', 'program', 'project', 'promote', 'proxy', 'publish',
    'query', 'queue', 'recover', 'reduce', 'refresh', 'register', 'remove',
    'render', 'replace', 'report', 'request', 'require', 'resolve', 'respond',
    'restart', 'restore', 'retrieve', 'return', 'reverse', 'revoke', 'rollback',
    'rotate', 'route', 'schedule', 'schema', 'scope', 'search', 'secure',
    'serialize', 'service', 'session', 'signal', 'socket', 'source', 'spawn',
    'split', 'start', 'status', 'stream', 'string', 'submit', 'subscribe',
    'switch', 'symbol', 'sync', 'terminate', 'thread', 'timeout', 'toggle',
    'token', 'trace', 'track', 'trigger', 'truncate', 'unsubscribe', 'update',
    'upload', 'validate', 'value', 'vector', 'verify', 'virtual', 'wait',
    'watch', 'write',
    // More complex words
    'access', 'account', 'achieve', 'acquire', 'action', 'active', 'actual',
    'address', 'advance', 'advice', 'affect', 'aggregate', 'agree', 'align',
    'analyze', 'apply', 'approach', 'article', 'assert', 'build', 'center',
    'change', 'check', 'choose', 'clear', 'close', 'compile', 'comply',
    'concern', 'control', 'create', 'critical', 'design', 'detect', 'direct',
    'discover', 'enable', 'expect', 'expose', 'follow', 'focus', 'format',
    'handle', 'improve', 'include', 'increase', 'initial', 'install', 'interact',
    'invoke', 'isolate', 'launch', 'limit', 'locate', 'manage', 'measure',
    'minimize', 'modify', 'monitor', 'move', 'observe', 'obtain', 'occur',
    'offer', 'order', 'parse', 'perform', 'persist', 'place', 'prevent',
    'produce', 'reduce', 'release', 'remove', 'resolve', 'restore', 'return',
    'reveal', 'review', 'rewrite', 'select', 'separate', 'shift', 'signal',
    'simplify', 'sort', 'specify', 'split', 'store', 'support', 'target', 'transfer',
    'unify', 'upgrade',
  ],
}
